# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish

on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  package-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Prepare C files to include
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements-cython.txt
          # Make sure we install to have all c files to be shiped with bundle
          python -m pip install -vv -Ue .  # We set -vv to see compiler exceptions/warnings
      - name: Build source package
        run: python setup.py sdist
      - name: Upload source package
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  package-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build wheels
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
          CIBW_BEFORE_BUILD_LINUX: pip install -r requirements-cython.txt && yum install -y zlib-devel
          # On windows and mac we should have z library preinstalled
          CIBW_BEFORE_BUILD: pip install -r requirements-cython.txt
          CIBW_BUILD_VERBOSITY: 2
        run: |
          python -m pip install --upgrade pip setuptools
          pip install cibuildwheel
          cibuildwheel --output-dir dist
        shell: bash
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:

    runs-on: ubuntu-latest
    needs: [package-source, package-wheel]

    steps:
      - uses: actions/checkout@v2
      - name: Download distributions
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
